# fly.toml app configuration file generated for wandering-dawn-1528 on 2023-11-07T21:20:10-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-dawn-1528"
primary_region = "sea"

[build]
image = "registry.fly.io/wandering-dawn-1528:0.1.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
